// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dkObx1-4RzUp6_CvncAGcz4fklPB4yQ',
    appId: '1:680930418161:web:a3388a0ddfaff4cf673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    authDomain: 'astro-darshan-a4ac5.firebaseapp.com',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
    measurementId: 'G-W8TLP503GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74WlX6tVXL6opjjQky8ZWnKfg9Shm2eY',
    appId: '1:680930418161:android:5ea1046e11e923dd673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKL3s9HKi6vP9_k_W3Ky0UV2qE4Ae-VyU',
    appId: '1:680930418161:ios:5052a8093b862da4673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
    iosBundleId: 'com.astrodarshan.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKL3s9HKi6vP9_k_W3Ky0UV2qE4Ae-VyU',
    appId: '1:680930418161:ios:3e43022c93868388673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
    iosBundleId: 'com.astrowaydiploy.user.astrology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeDkmzGs_XtFwh2NlWoaOhhb2PwG4IHFw',
    appId: '1:680930418161:web:48ce8ca00624b788673850',
    messagingSenderId: '680930418161',
    projectId: 'astro-darshan-a4ac5',
    authDomain: 'astro-darshan-a4ac5.firebaseapp.com',
    databaseURL: 'https://astro-darshan-a4ac5-default-rtdb.firebaseio.com',
    storageBucket: 'astro-darshan-a4ac5.appspot.com',
    measurementId: 'G-L4BE1BWEP9',
  );
}
